### ISSUE TITLE
Suggest spits JavaScript errors

### ISSUE THREAD

**Issue by codexp** [flagbit/Magento-FACTFinder#218] opened 2018-03-16 13:09 UTC
- FACT-Finder SDK version (see package.xml): 
```
<FACTFinder_Core>
    <version>4.0.1</version>
</FACTFinder_Core>
<FACTFinder_Suggest>
    <version>4.0.1</version>
</FACTFinder_Suggest>
```

- Magento edition and version: 
Magento CE Version 1.9.3.8

- PHP version: 
PHP 7.0.27

- Expected behavior: 
No JavaScript errors

- Actual behavior: 
a lot of
```
Error: Script failed to run [https://shop/ff_suggest/proxy/suggest/?query=112&format=JSONP&jquery_callback=jXHR.cb0&callback=jXHR.cb0].
Error: Script failed to load [https://shop/ff_suggest/proxy/suggest/?query=112&format=JSONP&jquery_callback=jXHR.cb0&callback=jXHR.cb0].
```
(maybe on first request only)

- Steps to reproduce: 

1. Open fresh tab to https://www.aktivshop.de
2. Enter "*123" onto search
3. watch console

**Comment by mbraeuner** [comment] 2018-04-10 15:13
regex special chars will cause this error. Problem has been solved on my local instance. After finish testing, I will create a branch for testing purpose for you.

**Comment by mbraeuner** [comment] 2018-04-11 11:46
Branch [issue-218](https://github.com/Flagbit/Magento-FACTFinder/tree/issue-218) should solve your problem. Please let me know, if it works for you.

**Comment by wesseloh-as** [comment] 2018-04-11 14:45
I've deployed that fix on our live system and unforunatelly it has not fixed the issue.
Still many JavaScript errors when using RegExp special chars.

**Comment by mbraeuner** [comment] 2018-04-12 08:33
With the provided issue-218 I can't reproduce it on my testing system.
It is hard to debug directly your scenario, because of merged and stripped js files. Do you have a test, stage or development system to debug it without merging the files?

**Comment by wesseloh-as** [comment] 2018-04-12 08:54
On my local system:

Search Query: `*1`

XHR Result:

    jXHR.cb0({"suggestions":[]});

Browser Console:

![image](https://user-images.githubusercontent.com/37796455/38666382-0b625544-3e3f-11e8-99f0-77f2d9984404.png)

PHP Logfile:

```
2018-04-12T10:04:57+02:00 DEBUG (7): >>>> ff_suggest/proxy/suggest => FACTFinder_Suggest_ProxyController->suggestAction
72018-04-12T10:04:58+02:00 WARN (4): FACTFinder json response is invalid! json_decode() raised an error: 4
```

suggest.js:


    298            var searchString = this.field.value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    299
    300            temp += item.name.replace(new RegExp("(" + searchString + ")", "ig"), '<strong>$1</strong>');

**Comment by wesseloh-as** [comment] 2018-04-12 08:57
We have no test/staging instances on our live server. (see recent e-mail from me)

**Comment by mbraeuner** [comment] 2018-06-18 16:58
I'm not shure about the whole functionality of that Autocomplete of Scriptaculous. There is a "changed" property which prevents adding the new items returned by the request.

This piece of code is an adopted copy of the original updateChoices method of the Autocomplete
[if(!this.changed && this.hasFocus)](https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/js/factfinder/suggest.js#L147)

If you type more than two letters fast into the input, the function will not add the result to the Autocomplete / Suggest.
If the result has not been added the [$('suggest-options').observe](https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/js/factfinder/suggest.js#L225) will throw an error.

First thing is prevent execution of observe() when `$('suggest-options').observe('mouseleave'` "suggest-options" does not exist. But this is not the root cause of the problem. The problem is that "suggest-options" does not exist for the first and second request. 

I tested the scripts after deleting the "this.changed" from condition in line 147.
Just change [if(this.hasFocus)](https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/js/factfinder/suggest.js#L147) 
Would be nice if could help an test if this change has some negative site effects while entering or deleting characters into the search field

**Comment by mbraeuner** [comment] 2018-08-31 13:33
Did you have time to test my proposal? 
Just to change 
`if(!this.changed && this.hasFocus) {`
to 
`if(this.hasFocus)`

**Comment by mbraeuner** [comment] 2019-01-07 15:20
the changes will be part of v 4.2.1
#234

**Closed by mbraeuner** 2019-01-07 15:20 UTC
