### ISSUE TITLE
Issue for Multistore Factfinder feedexport when catalog_product_flat table is used

### ISSUE THREAD

**Issue by gauravbrady** [flagbit/Magento-FACTFinder#239] opened 2019-08-29 11:11 UTC
- FACT-Finder SDK version (see package.xml): 
- Magento edition and version: Magento Enterprise 1.1
- PHP version: 7.2
- Expected behavior: Correct deeplink should be exported per store in a multi-store environment when flat product tables are used
- Actual behavior: Incorrect url generated for all but the first store due to use of the same flat table for all subsequent stores
- Steps to reproduce: Export Factfinder using --exportAll as an argument.

**Comment by gauravbrady** [comment] 2019-08-29 11:14
Once we try to export the feed in multistore using --exportAll, the getSearchableProducts method in src/app/code/community/FACTFinder/Core/Model/Export/Type/Product.php will always take the first store flat table.

**Comment by mbraeuner** [comment] 2019-09-10 07:53
Which extension version do you use? 
I setup a magento standard shop with sample data. Installed latest version. The standard shop has one website, one store group and three stores/store views. I added also one more test website with one further store group and another store.
![Auswahl_746](https://user-images.githubusercontent.com/29225156/64593609-a656fe00-d3ae-11e9-807c-415efe190542.png)
I switched "Use Flat Catalog Product" and "Use Flat Catalog Category" to yes. Reindexing.
All stores do have own subdomains. This will be respected executing the shell command with --exportAll switch.
Are there further steps you did to configure your multi store setup?

**Comment by mbraeuner** [comment] 2020-03-04 18:17
I'm not able to reproduce this issue wihout further information. I'll close it.

**Closed by mbraeuner** 2020-03-04 18:17 UTC
