### ISSUE TITLE
Class 'FACTFinder\Core\AbstractConfiguration' not found

### ISSUE THREAD

**Issue by boehsermoe** [flagbit/Magento-FACTFinder#226] opened 2018-07-16 12:40 UTC
Start the Cron Job I get follow error:

```
Warning: include(FACTFinder\Core\AbstractConfiguration.php): failed to open stream: No such file or directory in /var/www/html/htdocs/lib/Varien/Autoload.php on line 94

Warning: include(): Failed opening 'FACTFinder\Core\AbstractConfiguration.php' for inclusion (include_path='/var/www/html/htdocs/app/code/local:/var/www/html/htdocs/app/code/community:/var/www/html/htdocs/app/code/core:/var/www/html/htdocs/lib:.:') in /var/www/html/htdocs/lib/Varien/Autoload.php on line 94

Fatal error: Class 'FACTFinder\Core\AbstractConfiguration' not found in /var/www/html/vendor/flagbit/factfinder/src/lib/FACTFinderCustom/Configuration.php on line 9
TRIGGER: shutdown function
Last error: 
Array
(
    [type] => 1
    [message] => Class 'FACTFinder\Core\AbstractConfiguration' not found
    [file] => /var/www/html/vendor/flagbit/factfinder/src/lib/FACTFinderCustom/Configuration.php
    [line] => 9
)

```

**Comment by mbraeuner** [comment] 2018-07-16 12:53
Is it working if you start the job manually on shell?
Does you job change the directory before starting the script?

**Comment by boehsermoe** [comment] 2018-07-16 12:57
I execute the cron.sh in the project root directory.

**Comment by mbraeuner** [comment] 2018-07-24 10:14
The module is working in Shop. This exception only throwing if you execute the cron.sh?
Did you install magento with composer? Do you have a minimum setup to reproduce this error if you use composer?

**Comment by jriboux** [comment] 2018-09-13 08:49
Hello,

I have the same issue.
When generating the export from back office there is no error.
When using cron.sh I get the error "Class 'FACTFinder\Core\AbstractConfiguration' not found".

I tried including the lib/FACTFinder/Loader.php file in lib/FACTFinderCustom/Configuration.php , it solves the cron issue it is not usable from website.

The cron is *not* run using shell_exec but like that : 
```php
    Mage::getConfig()->init()->loadEventObservers('crontab');
    Mage::app()->addEventArea('crontab');
        Mage::dispatchEvent('always');
        Mage::dispatchEvent('default');
```

Any clue on how to fix this ?

Best regards,
Jonathan

**Comment by mbraeuner** [comment] 2018-09-25 16:14
Did you install magento and this extension via composer? I did a clean magento 1.9.3.10 demo store installation from scratch with this extension. The shedule sh script works fine for me. It looks like a problem with autoloading of factfinder's library. 
@boehsermoe Did you use /var/www/html/htdocs or /var/www/html as magento-root-dir?
@boehsermoe and @jriboux is your vendor folder inside magento root or one folder above?
Can you provide me a minimal composer.json to reproduce your installation, please?

**Comment by mbraeuner** [comment] 2019-01-07 14:09
I hit into the same problem in a different project and I figured out the problem. By running the cron the the event to add the autoloader will not be dispatched. 
I added some extra initialisation code to the export observer: https://github.com/flagbit/Magento-FACTFinder/commit/2294a953d3f072120336ce3b449e8fb0f5cc4a74

[branch issue-230](https://github.com/flagbit/Magento-FACTFinder/tree/issue-226)

**Comment by mbraeuner** [comment] 2019-01-07 15:22
the changes will be part of v 4.2.1
#235

**Closed by mbraeuner** 2019-01-07 15:22 UTC
