### ISSUE TITLE
validation of created data feeds

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#152] opened 2016-04-21 16:05 UTC
The data feeds should be written into a temporary file. Then it will be possible to make some validity checks.
- file not empty
- file header set
- amount of fields in first and last record identical
- amount of records according to database is identical to amount of rows

If the newly created product, stock and price feeds pass these checks, only then, the following steps should be triggered:
- replacing the existing files
- if FTP upload is enabled
  - creation of a new zip file which bundles the three files of a store
  - upload of the zip file
- triggering data import with sub-sequent import calls

**Comment by tuegeb** [comment] 2016-08-24 11:25
@xpoback: Any news regarding this issue? I am looking forward to your answer.

**Comment by xpoback** [comment] 2016-08-24 14:40
@tuegeb What should be done if any of the validity checks fails, except for writing this into logs?

**Comment by tuegeb** [comment] 2016-08-24 15:02
The resulting temporary CSV and/or ZIP file should be moved to a backup directory and each error message - which will additionally be logged - would show up in the Magento administration area. The following steps in this export/import process would be skipped.

For instance if the CSV file is broken, no new ZIP file will be created and no import trigger will be sent. 
Or if the ZIP file creation or upload fails, no import triggers will be sent.

**Comment by tuegeb** [comment] 2016-10-05 14:50
@DennisU 
@xpoback 
The temp file - tested on Windows - is never renamed, even if it is valid. If the delimiter, enclosure and escape characters are part of a field value, a row is not recognized as valid.

**Comment by xpoback** [comment] 2016-10-12 12:35
@tuegeb Do we really have customers who run Magento on Windows? I'm just wondering.

**Comment by xpoback** [comment] 2016-10-12 13:04
@tuegeb Regarding the other issue, in my tests escape characters couldn't make row validation to fail, as well as enclosure character. Delimiter breaks validation when it's not enclosed, but this is correct.
Could you please provide me a specific example, so I would reproduce and fix this problem?

**Comment by tuegeb** [comment] 2016-10-12 19:17
@xpoback: 
At least one of my QA environments is using xampp on Windows. Therefore I would like to see a plattform independent implementation. If it isn't possible, the mentioned workaround for Windows would be sufficient.

Regarding the invalid feed: Simply copy and paste the contents of an existing product.csv into the field "Description" of a product inside Magento in order to simulate bad data. The record of the corresponding product will be detected as invalid.

**Comment by xpoback** [comment] 2016-11-03 17:23
@tuegeb The problem was that the enclosure symbol (") was escaped every time it was written to the file by the default function `fputscv` so `\"` became `\\"`. But then the function `fgetcsv` interpreted it as an escaped slash and a "free" double quote, which broke the field into pieces.
An example, where data written to the file and read from there by basic native functions can be different.

I added a simple replace for that and it appeared to have helped.
Also, the Windows fix has been added, so please, test it.

**Comment by tuegeb** [comment] 2016-11-03 18:09
@xpoback: Thanks, both issues have been solved. However in the following a suggestion:

Maybe the string replacements in https://github.com/Flagbit/Magento-FACTFinder/blob/9a8c75c58bf0bdf18fb2acff23d828ca128aba86/src/app/code/community/FACTFinder/Core/Model/Export/Type/Product.php#L126 should be moved to https://github.com/Flagbit/Magento-FACTFinder/blob/9a8c75c58bf0bdf18fb2acff23d828ca128aba86/src/app/code/community/FACTFinder/Core/Model/File.php#L175.

**Comment by xpoback** [comment] 2016-11-04 10:24
@tuegeb Yes, you're right. Done.

**Comment by xpoback** [comment] 2016-11-04 12:32
@tuegeb Would it make sense to make validation optional (in case there are unexpected troubles)?

**Comment by tuegeb** [comment] 2016-11-04 17:58
@xpoback: That's a good idea. However the validation should be enabled per default.

A related export/import issue:
If the module is enabled only for some of the stores (= disabled in the default configuration), the exports (stock, price and product) are made for all stores when using the shell script. When using https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/shell/factfinder.php#L8 the export with validation and the import triggers should only be made for the stores which have FACT-Finder enabled. Could you fix that, please? Many thanks.

**Closed** 2016-11-15 19:03 UTC
Labels: improvement
